### ISSUE TITLE
Platform independence

### ISSUE THREAD

**Issue by emoon** [rust-qt/ritual#6]
Right now the Qt libs becomes platform dependent depending on where it was compiled.

qt.rs over here https://github.com/kitech/qt.rs/blob/master/src/gui/qcolor.rs#L570 solves it this way

``` Rust
  // proto:  void QColor::QColor(const char * name);
impl<'a> /*trait*/ QColor_new for (&'a  String) {
  fn new(self) -> QColor {
    // let qthis: *mut c_void = unsafe{calloc(1, 32)};
    // unsafe{_ZN6QColorC2EPKc()};
    let ctysz: c_int = unsafe{QColor_Class_Size()};
    let qthis_ph: u64 = unsafe{calloc(1, ctysz as usize)} as u64;
    let arg0 = self.as_ptr()  as *mut c_char;
    let qthis: u64 = unsafe {C_ZN6QColorC2EPKc(arg0)};
    let rsthis = QColor{qclsinst: qthis, ..Default::default()};
    return rsthis;
    // return 1;
  }
}
```

By having generated a function that returns a size of the object (which is in the FFI code including the C++ headers) and here doing a calloca here to allocate zeroed memory.

Of course the backside of this approach is that when using objects like this they now need to be allocated on the heap which adds run-time overhead.

Not sure if this is something worth investigating or not.

**Comment by Riateche** [comment]
It's already possible to create objects on the heap if you pass `CppPointer` as an argument. For heap-allocated objects size information does not matter because they are created and deleted on C++ side, so they indeed are more portable. I'm not sure why `calloc` and the class size function may be needed here. I just call `new` in the C++ wrapper and return the pointer.

Stack allocation of C++ objects in Rust is more dangerous not only because object size can be different, but also because Rust can move the object in memory, and not all C++ objects allow that. For example, you can safely use stack-allocated `QPoint` in Rust, but stack-allocated `QApplication` will cause a crash. I think we'll need to add either annotations or semi-automatic detection of such classes and disable option to stack-allocate them.

**Comment by emoon** [comment]
I see. I was thinking if there was a way we could get the qt_core/gui/widget crates platform independent. Building separate versions for different OSes is doable but the process is quite slow. It would be much nicer if it was possible to actually include the generated Rust and C++ wrapper files in the qt_core/gui/widgets so the user wouldn't need to generate them.

**Comment by Riateche** [comment]
I was originally planning to generate cross-platform code. It definitely should be done, but I've decided to put it on hold for now because it's hard and it would be nice to make the project work at least somewhere.

Total number of toolchains is a bit scary. On Windows, Qt is built separately for each version of MSVC and for MinGW. Some methods suddently appear depending on a lot of unexpected parameters. Class sizes change unpredictably. How many toolchains will it need to process to make it work everywhere? And will it actually work?

On the other side, processing on the native system doesn't really provide a strong guarantee that it will work correctly. It's because it uses clang interface instead of the compiler Qt really was built on. Clang 3.8 can't parse MSVC 2015 headers (but clang 3.9 can). Clang's pre-built binaries on Windows don't even have MinGW support! How can I know that it'll generate meaningful results? I may as well just run clang on Linux.

Qt also has special methods on each platform. Some methods are available on Mac OS only because they work with Mac OS's native types. But some methods suddenly appear just because clang is "good enough" to have them. And now we have `QByteArray QString::toLocal8Bit()` in addition to `QByteArray QString::toLocal8Bit() const`, but only on Mac OS, so Rust's method `to_local_8bit` suddenly is renamed to `to_local_8bit_from_const` because of a name conflict. How am I supposed to write a cross-platform Rust code now? No way. I had to blacklist the non-const method, but it's just a temporary solution.

So, current approach doesn't really offer any portability just because API is not stable. To make API uniform on all platforms, we need to run clang parser on all platforms and merge the results. Both steps are not easy tasks at all. We can either do it all on one platform, but clang will need to be set up in cross-compilation mode for each of target toolchains, or just run it natively on each platform, as I try to do now. The latter approach allows me to make some initial support of the platform, so I'm taking this path.

But even after that, we'll need to check if every available method is available on current platform and acquire real sizes of classes. It can be done using the toolchain's compiler though, without clang's shenanigans. If a method is not present, we can use Rust's feature system to tell the user that it's not available, so that they can use conditional compilation to work around that issue. That would be an awful lot of features, though. I'm not sure it's a good idea.

So, the current goal is to make it somehow work on each supported platform without any promises of portability. After that is a bit stabilized, we'll have the freedom to explore our options of making a truly portable wrapper.

**Comment by emoon** [comment]
Thanks for a lengthy reply :) Yes that makes sense.

**Comment by Riateche** [comment]
## Current plan of implementation

### Populating parse information
We need to populate all C++ information (available classes and methods, sizes of structs, values of enums, etc.) for every supported toolchain and library version. This requires a working C++ compiler for the platform. It will be done either by cross-compilation or by running on all platforms natively. Output files will contain information about the toolchain and library version.

### Combining information
All parse results should be combined by analyzing them together. For every change in struct size, enum variants, or method signature the analyzer will collect all possible variants and figure out the simplest condition for each variant. For example, if a method is only available on Window, the analyzer will mark it as `if os=win`. If there are two variants for 32-bit and 64-bit systems, but OS doesn't matter, the analyzer should be able to figure it out and create two variants with `if ptrsize=32` and `if ptrsize=64` conditions. Note that method signatures use `libc` types, and methods with the same types will be considered the same even if corresponding `libc` type is different on different platforms.

Method name resolution also depends on combined information. If two methods should have prefixes because of a name conflict, and one of methods does not exist on some conditions, the other method should still have the same prefix on all platforms. The same applies to renaming enum variants, where adding or removing a variant could cause other variants to change name.

### Generating code
This information allows to generate platform-independent code. The code will always include all encountered versions of parse results. Every portion of parse result that was detected to depend on toolchain or library version will be wrapped in a conditional compilation statement. 

In Rust, the conditions will be generated using `#[cfg]` attributes. Toolchain conditions will be generated as usual, and library version conditions will use crate features. The build script will auto-detect current library version and set the features accordingly.

Conditions will appear in Rust documentation and source code of the crate. The users can examine conditions and apply workarounds for unsupported cases.

In C++ wrapper code, conditions will be translated to `#ifdef` directives. Information about toolchain and library version will be passed from the build script to C++ wrapper by adding definitions.

If the crate is being built with an unknown toolchain or library version, the build script will produce the warning but still attempt to build the crate.

### One-platform mode
The generator should still support one-platform mode where the crate is intended to be used only on the same platform where it was generated. In this case no conditions will be generated, but the rest of implementation will be the same.

**Comment by Riateche** [comment]
`cpp_to_rust` now generates somewhat cross-platform code. The following tasks remain important:

- Implement some sort of API freezing to ensure that processing a future version of the C++ library will produce backwards-compatible API.
- Support conditionally available types and methods based on target platform and current library version. Provide access to Qt's platform-specific APIs.

**Comment by Riateche** [comment]
Platform independence is now more or less achieved. It turns out Qt doesn't have many differences on different OSs, and trying to analyze the API on all platforms is way too resource consuming. So the solution now is to analyze it on Linux and just make sure it builds on other systems via CI.

The generated crates can now work with different Qt versions. We generate `#[cfg]` attributes that enable some parts of the API only when Qt version is appropriate. This will hopefully allow everyone to use the same generated crates. If you use a recent Qt version, you have the latest API avaiable. And if you're on an older version, it still works, just with new API disabled.
