### ISSUE TITLE
Learning opportunities

### ISSUE THREAD

**Issue by Serentty** [rust-qt/ritual#89]
Right now, I'm having a fair amount of trouble mapping the Qt documentation to the code that I would need to write in Rust. I get that it's too early to be writing lots of Rust-specific documentation when this project is still very unstable, and the same goes for writing more examples, but what about something like an IRC channel or Discord server where people could help each other get off their feet in terms of figuring out this API?

**Comment by Riateche** [comment]
I don't think I have enough time to support an official Discord server. I don't think it will be very likely to find an answer there because the audience is very small. GitHub and [URLO](https://users.rust-lang.org/) already have some audience, are easily accessible and indexed by Google, so they seem like a far better place for discussion than a Discord server.

**Comment by Serentty** [comment]
I worry about creating too many issues and flooding things with trivial questions, but if that's the easier way, then I'm okay with it.

**Comment by Riateche** [comment]
I don't see any harm in opening issues. Everyone should feel free to open a new issue if they need help.

We'll consider opening an official community channel if the community grows large enough.
