### ISSUE TITLE
Missing Slot types?

### ISSUE THREAD

**Issue by jlgerber** [rust-qt/ritual#90]
QTableWidget has a number of slots that don't look like they are covered in the core SlotOf... list. For instance, here is the signature for a signal:
```
void QTableWidget::currentItemChanged(QTableWidgetItem *current, QTableWidgetItem *previous)
```
What would one use to define a slot that works with this signal?

**Comment by jlgerber** [comment]
Realized that I don't really need to use this given that i can get the selection model and go from there...

**Comment by Riateche** [comment]
These slot wrappers can't be provided by `qt_core` because `qt_core` doesn't have `QTableWidgetItem` type. Each crate provides its own slot wrappers for arguments that are not covered by its dependencies.  For `QTableWidget::currentItemChanged`, the corresponding slot wrapper is [qt_widgets::SlotOfQTableWidgetItemQTableWidgetItem](https://docs.rs/qt_widgets/0.4.0/qt_widgets/struct.SlotOfQTableWidgetItemQTableWidgetItem.html).
