### ISSUE TITLE
QMenu missing add_action_action

### ISSUE THREAD

**Issue by jlgerber** [rust-qt/ritual#91]
Missing ability to add an  pointer to an existing QAction into the menu in order to reuse actions.

**Comment by Riateche** [comment]
It's [here](https://docs.rs/qt_widgets/0.4.0/qt_widgets/struct.QMenu.html#method.add_action). It's just called `add_action`. The naming is different because this method is inherited from `QWidget` and isn't overloaded for `QWidget`. Only `QMenu`'s methods are overloaded, so only they have disambiguated names.

**Comment by jlgerber** [comment]
awesome. Thank you!
